import { saveSettingsAction } from "@/app/actions";
import { PageHeader } from "@/components/app-shell";
import { db } from "@/db";
import { settings } from "@/db/schema";

export default async function SettingsPage({searchParams}:{searchParams:Promise<{error?:string}>}) {
  const {error}=await searchParams;
  const [s]=await db.select().from(settings).limit(1);
  return <><PageHeader eyebrow="Workspace" title="Business settings"/><div className="content" style={{maxWidth:920}}>{error&&<div className="alert">{error}</div>}<form action={saveSettingsAction} className="grid">
    <section className="card card-pad grid"><div><div className="eyebrow">Identity</div><h2 style={{marginTop:5}}>Shown on invoices</h2></div><div className="form-row"><div className="field"><label>Business name</label><input className="input" name="businessName" required defaultValue={s?.businessName}/></div><div className="field"><label>Your name</label><input className="input" name="ownerName" defaultValue={s?.ownerName}/></div></div><div className="form-row"><div className="field"><label>Email</label><input className="input" type="email" name="email" defaultValue={s?.email}/></div><div className="field"><label>Phone</label><input className="input" name="phone" defaultValue={s?.phone}/></div></div><div className="field"><label>Business address</label><textarea className="input" name="address" defaultValue={s?.address}/></div><div className="field"><label>Logo (PNG or JPEG, 2MB max)</label><input className="input" type="file" name="logo" accept="image/png,image/jpeg"/><span className="small muted">{s?.logoPath?"A logo is currently saved. Upload another to replace it.":"Optional; shown on generated invoices."}</span></div></section>
    <section className="card card-pad grid"><div><div className="eyebrow">Invoice defaults</div><h2 style={{marginTop:5}}>Billing rules</h2></div><div className="grid grid-3"><div className="field"><label>Currency</label><input className="input" name="currency" maxLength={3} defaultValue={s?.currency??"USD"}/></div><div className="field"><label>Tax rate (%)</label><input className="input" type="number" step="0.01" min="0" name="taxRate" defaultValue={(s?.taxBps??0)/100}/></div><div className="field"><label>Payment terms (days)</label><input className="input" type="number" min="0" name="paymentTermsDays" defaultValue={s?.paymentTermsDays??30}/></div></div><div className="form-row"><div className="field"><label>Invoice prefix</label><input className="input" name="invoicePrefix" maxLength={12} defaultValue={s?.invoicePrefix??"INV"}/></div><div className="field"><label>Timezone</label><input className="input" name="timezone" defaultValue={s?.timezone??"America/Denver"}/></div></div><div className="field"><label>Payment instructions</label><textarea className="input" name="paymentInstructions" defaultValue={s?.paymentInstructions} placeholder="Bank transfer or check details shown on every invoice."/></div></section>
    <button className="btn btn-primary" style={{justifySelf:"start"}}>Save settings</button>
  </form></div></>;
}
