import { and, desc, eq, isNull, sql } from "drizzle-orm";
import { Play, Square, Trash2 } from "lucide-react";
import { addTimeAction, deleteTimeAction, startTimerAction, stopTimerAction, updateTimeAction } from "@/app/actions";
import { AddModal } from "@/components/add-modal";
import { db } from "@/db";
import { clients, invoiceTimeEntries, projects, settings, timeEntries } from "@/db/schema";
import { PageHeader } from "@/components/app-shell";
import { TimerClock } from "@/components/timer-clock";
import { formatDateTime, formatDuration } from "@/lib/money";
import { formatInTimeZone } from "date-fns-tz";
import { requireUser } from "@/lib/auth";

export default async function TimePage({searchParams}:{searchParams:Promise<{error?:string}>}) {
  const user=await requireUser(); const {error}=await searchParams;
  const [business]=await db.select({timezone:settings.timezone}).from(settings).limit(1); const timezone=business?.timezone??"America/Denver";
  const activeProjects=await db.select({project:projects,client:clients}).from(projects).innerJoin(clients,eq(projects.clientId,clients.id)).where(and(eq(projects.archived,false),eq(clients.archived,false))).orderBy(clients.name,projects.name);
  const [active]=await db.select({entry:timeEntries,project:projects,client:clients}).from(timeEntries).innerJoin(projects,eq(timeEntries.projectId,projects.id)).innerJoin(clients,eq(projects.clientId,clients.id)).where(and(eq(timeEntries.userId,user.id),isNull(timeEntries.endedAt))).limit(1);
  const entries=await db.select({entry:timeEntries,project:projects,client:clients,billed:invoiceTimeEntries.invoiceId}).from(timeEntries).innerJoin(projects,eq(timeEntries.projectId,projects.id)).innerJoin(clients,eq(projects.clientId,clients.id)).leftJoin(invoiceTimeEntries,eq(timeEntries.id,invoiceTimeEntries.timeEntryId)).where(sql`${timeEntries.endedAt} is not null`).orderBy(desc(timeEntries.startedAt)).limit(50);
  const local=formatInTimeZone(new Date(),timezone,"yyyy-MM-dd'T'HH:mm");
  const manualTimeForm=<form action={addTimeAction} className="grid"><div className="field"><label>Project</label><select name="projectId" className="input" required defaultValue=""><option value="" disabled>Choose a project</option>{activeProjects.map(({project,client})=><option value={project.id} key={project.id}>{client.name} — {project.name}</option>)}</select></div><div className="field"><label>Started</label><input type="datetime-local" name="startedAt" defaultValue={local} className="input" required/></div><div className="form-row"><div className="field"><label>Hours</label><input type="number" name="hours" min="0" defaultValue="1" className="input"/></div><div className="field"><label>Minutes</label><input type="number" name="minutes" min="0" max="59" defaultValue="0" className="input"/></div></div><div className="field"><label>Description</label><input name="notes" className="input" placeholder="What was completed?"/></div><label className="small"><input type="checkbox" name="billable" defaultChecked/> Billable</label><button className="btn btn-primary" style={{justifySelf:"end"}}>Add time</button></form>;
  return <><PageHeader eyebrow="Time" title="Track the work" action={<AddModal title="Add finished time" triggerLabel="Add time" disabled={!activeProjects.length}>{manualTimeForm}</AddModal>}/><div className="content">
    {error&&<div className="alert">{error}</div>}
    <div className="card timer-card">{active?<><div><div className="eyebrow">Running</div><h2 style={{marginTop:5}}>{active.project.name}</h2><div className="small muted">{active.client.name} · {active.entry.notes||"No description"}</div></div><TimerClock startedAt={active.entry.startedAt.toISOString()}/><form action={stopTimerAction}><button className="btn btn-danger"><Square size={15}/> Stop</button></form></>:<form action={startTimerAction} style={{display:"contents"}}><div className="field"><label htmlFor="notes">What are you working on?</label><input id="notes" className="input" name="notes" placeholder="Design review, client call…"/></div><div className="field"><label htmlFor="projectId">Project</label><select id="projectId" name="projectId" className="input" required defaultValue=""><option value="" disabled>Choose a project</option>{activeProjects.map(({project,client})=><option value={project.id} key={project.id}>{client.name} — {project.name}</option>)}</select></div><div><label className="small" style={{display:"block",marginBottom:8}}><input type="checkbox" name="billable" defaultChecked/> Billable</label><button className="btn btn-primary"><Play size={15}/> Start timer</button></div></form>}</div>
    <div className="section-head"><div><div className="eyebrow">Log</div><h2>Recent entries</h2></div></div><div className="card table-wrap">{entries.length?<table><thead><tr><th>Project</th><th>Date</th><th>Duration</th><th>Status</th><th></th></tr></thead><tbody>{entries.map(({entry,project,client,billed})=><tr key={entry.id}><td><b>{project.name}</b><div className="small muted">{client.name} · {entry.notes||"No description"}</div>{!billed&&<details style={{marginTop:8}}><summary className="small" style={{cursor:"pointer",color:"var(--accent)",fontWeight:700}}>Edit entry</summary><form action={updateTimeAction} className="grid" style={{paddingTop:12,minWidth:290}}><input type="hidden" name="id" value={entry.id}/><select className="input" name="projectId" defaultValue={entry.projectId}>{activeProjects.map(({project:p,client:c})=><option key={p.id} value={p.id}>{c.name} — {p.name}</option>)}</select><input className="input" type="datetime-local" name="startedAt" defaultValue={formatInTimeZone(entry.startedAt,timezone,"yyyy-MM-dd'T'HH:mm")}/><input className="input" type="number" min="1" name="durationMinutes" defaultValue={Math.round((entry.durationSeconds??0)/60)}/><input className="input" name="notes" defaultValue={entry.notes}/><label className="small"><input type="checkbox" name="billable" defaultChecked={entry.billable}/> Billable</label><button className="btn btn-secondary">Save changes</button></form></details>}</td><td>{formatDateTime(entry.startedAt,timezone)}</td><td>{formatDuration(entry.durationSeconds??0)}</td><td>{billed?<span className="badge sent">Invoiced</span>:entry.billable?<span className="badge draft">Unbilled</span>:<span className="badge">Non-billable</span>}</td><td>{!billed&&<form action={deleteTimeAction}><input type="hidden" name="id" value={entry.id}/><button className="btn btn-ghost" aria-label="Delete entry"><Trash2 size={14}/></button></form>}</td></tr>)}</tbody></table>:<div className="empty">No finished entries yet.</div>}</div>
  </div></>;
}
